/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package segundoadelanto;

import javax.swing.JOptionPane;
import proyecto.Principal;

/**
 *
 * @author USUARIO
 */
public class conceptos extends javax.swing.JFrame {

    /**
     * Creates new form conceptos
     */
    public conceptos() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabelc14 = new javax.swing.JLabel();
        Panelconceptos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelc1 = new javax.swing.JLabel();
        jLabelc2 = new javax.swing.JLabel();
        jLabelc3 = new javax.swing.JLabel();
        jLabelc4 = new javax.swing.JLabel();
        jLabelc5 = new javax.swing.JLabel();
        jLabelc6 = new javax.swing.JLabel();
        jLabelc7 = new javax.swing.JLabel();
        jLabelc8 = new javax.swing.JLabel();
        jLabelc9 = new javax.swing.JLabel();
        jLabelc10 = new javax.swing.JLabel();
        jLabelc11 = new javax.swing.JLabel();
        jLabelc12 = new javax.swing.JLabel();
        jLabelc15 = new javax.swing.JLabel();
        jLabelc16 = new javax.swing.JLabel();
        Buttonsalir = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabelc14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelc14.setForeground(new java.awt.Color(255, 255, 255));
        jLabelc14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelc14.setText("jLabel4");
        jLabelc14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabelc14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelc14MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panelconceptos.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Conceptos ");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabelc1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelc1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelc1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelc1.setText("FrameWork");
        jLabelc1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabelc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelc1MouseClicked(evt);
            }
        });

        jLabelc2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelc2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelc2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelc2.setText("POO");
        jLabelc2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabelc2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelc2MouseClicked(evt);
            }
        });

        jLabelc3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelc3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelc3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelc3.setText("JavaSwing");
        jLabelc3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabelc3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelc3MouseClicked(evt);
            }
        });

        jLabelc4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelc4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelc4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelc4.setText("Herencia");
        jLabelc4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabelc4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelc4MouseClicked(evt);
            }
        });

        jLabelc5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelc5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelc5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelc5.setText("CamelCase");
        jLabelc5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabelc5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelc5MouseClicked(evt);
            }
        });

        jLabelc6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelc6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelc6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelc6.setText("UML");
        jLabelc6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabelc6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelc6MouseClicked(evt);
            }
        });

        jLabelc7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelc7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelc7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelc7.setText("BackEnd");
        jLabelc7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabelc7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelc7MouseClicked(evt);
            }
        });

        jLabelc8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelc8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelc8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelc8.setText("Abstraccion");
        jLabelc8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabelc8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelc8MouseClicked(evt);
            }
        });

        jLabelc9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelc9.setForeground(new java.awt.Color(255, 255, 255));
        jLabelc9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelc9.setText("FrontEnd");
        jLabelc9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabelc9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelc9MouseClicked(evt);
            }
        });

        jLabelc10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelc10.setForeground(new java.awt.Color(255, 255, 255));
        jLabelc10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelc10.setText("Github");
        jLabelc10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabelc10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelc10MouseClicked(evt);
            }
        });

        jLabelc11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelc11.setForeground(new java.awt.Color(255, 255, 255));
        jLabelc11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelc11.setText("colecciones");
        jLabelc11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabelc11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelc11MouseClicked(evt);
            }
        });

        jLabelc12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelc12.setForeground(new java.awt.Color(255, 255, 255));
        jLabelc12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelc12.setText("API");
        jLabelc12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabelc12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelc12MouseClicked(evt);
            }
        });

        jLabelc15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelc15.setForeground(new java.awt.Color(255, 255, 255));
        jLabelc15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelc15.setText("Encapsulamiento");
        jLabelc15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabelc15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelc15MouseClicked(evt);
            }
        });

        jLabelc16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelc16.setForeground(new java.awt.Color(255, 255, 255));
        jLabelc16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelc16.setText("Polimorfismo");
        jLabelc16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jLabelc16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelc16MouseClicked(evt);
            }
        });

        Buttonsalir.setText("Salir");
        Buttonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelconceptosLayout = new javax.swing.GroupLayout(Panelconceptos);
        Panelconceptos.setLayout(PanelconceptosLayout);
        PanelconceptosLayout.setHorizontalGroup(
            PanelconceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelconceptosLayout.createSequentialGroup()
                .addGroup(PanelconceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelconceptosLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel1))
                    .addGroup(PanelconceptosLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabelc4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelconceptosLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabelc15)
                        .addGap(43, 43, 43)
                        .addComponent(jLabelc16))
                    .addGroup(PanelconceptosLayout.createSequentialGroup()
                        .addGroup(PanelconceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelconceptosLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addGroup(PanelconceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelc7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelc10, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelconceptosLayout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabelc1)))
                        .addGroup(PanelconceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelconceptosLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabelc2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addGroup(PanelconceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelc9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelc12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelc3)
                                    .addComponent(jLabelc6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelconceptosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(PanelconceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelc8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelc5, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                    .addComponent(jLabelc11, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelconceptosLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Buttonsalir)
                .addGap(16, 16, 16))
        );
        PanelconceptosLayout.setVerticalGroup(
            PanelconceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelconceptosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGroup(PanelconceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelconceptosLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(PanelconceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelc1)
                            .addComponent(jLabelc3)))
                    .addGroup(PanelconceptosLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabelc2)))
                .addGap(21, 21, 21)
                .addGroup(PanelconceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelc4)
                    .addComponent(jLabelc6))
                .addGroup(PanelconceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelconceptosLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(PanelconceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelc7)
                            .addComponent(jLabelc9))
                        .addGap(32, 32, 32)
                        .addGroup(PanelconceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelc12)
                            .addComponent(jLabelc10)))
                    .addGroup(PanelconceptosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelc5)
                        .addGap(44, 44, 44)
                        .addComponent(jLabelc8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelc11)
                .addGap(19, 19, 19)
                .addGroup(PanelconceptosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelc15)
                    .addComponent(jLabelc16))
                .addGap(18, 18, 18)
                .addComponent(Buttonsalir)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panelconceptos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panelconceptos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabelc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelc1MouseClicked
        String mensajefr = """
                  Un esquema o marco de trabajo proporciona una estructura base para elaborar un proyecto 
                  con objetivos específicos, una especie de plantilla que sirve como punto de partida 
                  para la organización y desarrollo de software.
                  """;
        
        JOptionPane.showMessageDialog(null, mensajefr, "Esquema de Trabajo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabelc1MouseClicked

    private void jLabelc2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelc2MouseClicked
        String mensajepoo = """
                  La programación orientada a objetos. Paradigma de programación que usa 
                  objetos para crear aplicaciones.
                  """;
        JOptionPane.showMessageDialog(null, mensajepoo, "Esquema de Trabajo", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jLabelc2MouseClicked

    private void jLabelc3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelc3MouseClicked
        String mensajejs = """
                  Biblioteca de clases que permite crear interfaces gráficas de usuario 
                  en Java.
                  """;
        
        JOptionPane.showMessageDialog(null, mensajejs, "Esquema de Trabajo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabelc3MouseClicked

    private void jLabelc4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelc4MouseClicked
        String mensajeHe = """
                  Mecanismo por el cual una clase permite heredar las características 
                  (atributos y métodos) de otra clase.
                  """;
        JOptionPane.showMessageDialog(null, mensajeHe, "Esquema de Trabajo", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jLabelc4MouseClicked

    private void jLabelc5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelc5MouseClicked
        String mensajecc = """
                  Convención de escritura utilizada principalmente en programación para 
                  formar nombres de variables, funciones u otros identificadores compuestos 
                  por múltiples palabras.
                  """;
        
        JOptionPane.showMessageDialog(null, mensajecc, "Esquema de Trabajo", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jLabelc5MouseClicked

    private void jLabelc6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelc6MouseClicked
        String mensajeuml = """
                  Lenguaje de modelado visual común y semántica y sintácticamente rico para 
                  la arquitectura, el diseño y la implementación de sistemas de software 
                  complejos, tanto en estructura como en comportamiento.
                  """;
        JOptionPane.showMessageDialog(null, mensajeuml, "Esquema de Trabajo", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jLabelc6MouseClicked

    private void jLabelc7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelc7MouseClicked
        String mensajebe = """
                  Parte de un sistema informático o de software que está encargada de procesar 
                  los datos y lógica de negocio que no son visibles para el usuario final.
                  """;
        JOptionPane.showMessageDialog(null, mensajebe, "Esquema de Trabajo", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jLabelc7MouseClicked

    private void jLabelc8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelc8MouseClicked
        String mensajeabs = """
                  Capacidad de un lenguaje de programación para ocultar los detalles de 
                  implementación y mostrar solo los detalles esenciales del programa.
                  """;
        JOptionPane.showMessageDialog(null, mensajeabs, "Esquema de Trabajo", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jLabelc8MouseClicked

    private void jLabelc9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelc9MouseClicked
        String mensajefe = """
                  Parte de un sistema informático o de software que interactúa directamente 
                  con el usuario final.
                  """;
        JOptionPane.showMessageDialog(null, mensajefe, "Esquema de Trabajo", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jLabelc9MouseClicked

    private void jLabelc10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelc10MouseClicked
        String mensajegit = """
                  Plataforma online de desarrollo de software que se usa para almacenar, 
                  supervisar y trabajar con proyectos de software.
                  """;
        JOptionPane.showMessageDialog(null, mensajegit, "Esquema de Trabajo", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jLabelc10MouseClicked

    private void jLabelc11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelc11MouseClicked
        String mensajecole = """
                  Conjunto de elementos que se agrupan y manipulan como una sola unidad.
                  """;
        JOptionPane.showMessageDialog(null, mensajecole, "Esquema de Trabajo", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jLabelc11MouseClicked

    private void jLabelc12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelc12MouseClicked
        String mensajeapi = """
                  Conjunto de clases, interfaces, métodos y constantes que proporcionan una 
                  funcionalidad específica para ser utilizada por otras aplicaciones o módulos 
                  de software.
                  """;
        JOptionPane.showMessageDialog(null, mensajeapi, "Esquema de Trabajo", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jLabelc12MouseClicked

    private void jLabelc14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelc14MouseClicked
        JOptionPane.showMessageDialog(rootPane, "14");
    }//GEN-LAST:event_jLabelc14MouseClicked

    private void jLabelc15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelc15MouseClicked
        String mensajeEc = """
                  Consiste en agrupar los datos (atributos) y los métodos (comportamientos) 
                  relacionados con un objeto dentro de una sola unidad, llamada clase.
                  """;
        JOptionPane.showMessageDialog(null, mensajeEc, "Esquema de Trabajo", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jLabelc15MouseClicked

    private void jLabelc16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelc16MouseClicked
        String mensajepol = """
                  Capacidad que tienen ciertos lenguajes para hacer que, al enviar el mismo 
                  mensaje (o, en otras palabras, invocar al mismo método) desde distintos 
                  objetos, cada uno de esos objetos pueda responder a ese mensaje (o a esa 
                  invocación) de forma distinta.
                  """;
        JOptionPane.showMessageDialog(null, mensajepol, "Esquema de Trabajo", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_jLabelc16MouseClicked

    private void ButtonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonsalirActionPerformed
        Principal principalFrame = new Principal();
            principalFrame.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_ButtonsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(conceptos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(conceptos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(conceptos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(conceptos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new conceptos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttonsalir;
    private javax.swing.JPanel Panelconceptos;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelc1;
    private javax.swing.JLabel jLabelc10;
    private javax.swing.JLabel jLabelc11;
    private javax.swing.JLabel jLabelc12;
    private javax.swing.JLabel jLabelc14;
    private javax.swing.JLabel jLabelc15;
    private javax.swing.JLabel jLabelc16;
    private javax.swing.JLabel jLabelc2;
    private javax.swing.JLabel jLabelc3;
    private javax.swing.JLabel jLabelc4;
    private javax.swing.JLabel jLabelc5;
    private javax.swing.JLabel jLabelc6;
    private javax.swing.JLabel jLabelc7;
    private javax.swing.JLabel jLabelc8;
    private javax.swing.JLabel jLabelc9;
    // End of variables declaration//GEN-END:variables
}
