/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto;

import javax.swing.JOptionPane;
import proyecto.iniciar;



 
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panellogin = new javax.swing.JPanel();
        jPanellog = new javax.swing.JPanel();
        Labelnombre = new javax.swing.JLabel();
        TextFieldnom = new javax.swing.JTextField();
        Labelcontra = new javax.swing.JLabel();
        PasswordFieldcontra = new javax.swing.JPasswordField();
        Buttonlogin = new javax.swing.JButton();
        Buttonotrousuario = new javax.swing.JButton();
        Labelnombre1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panellogin.setBackground(new java.awt.Color(51, 51, 51));

        jPanellog.setBackground(new java.awt.Color(102, 102, 102));

        Labelnombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Labelnombre.setForeground(new java.awt.Color(255, 255, 255));
        Labelnombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labelnombre.setText("Nombre de usuario");

        TextFieldnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldnomActionPerformed(evt);
            }
        });

        Labelcontra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Labelcontra.setForeground(new java.awt.Color(255, 255, 255));
        Labelcontra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labelcontra.setText("Contraseña");

        PasswordFieldcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldcontraActionPerformed(evt);
            }
        });

        Buttonlogin.setText("login");
        Buttonlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanellogLayout = new javax.swing.GroupLayout(jPanellog);
        jPanellog.setLayout(jPanellogLayout);
        jPanellogLayout.setHorizontalGroup(
            jPanellogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellogLayout.createSequentialGroup()
                .addGroup(jPanellogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanellogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Labelcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanellogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanellogLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(Labelnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanellogLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(TextFieldnom, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanellogLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanellogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Buttonlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordFieldcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanellogLayout.setVerticalGroup(
            jPanellogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanellogLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Labelnombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextFieldnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Labelcontra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordFieldcontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(Buttonlogin)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        Buttonotrousuario.setText("Crear otro usuario");
        Buttonotrousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonotrousuarioActionPerformed(evt);
            }
        });

        Labelnombre1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Labelnombre1.setForeground(new java.awt.Color(255, 255, 255));
        Labelnombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labelnombre1.setText("Bienvenido");

        javax.swing.GroupLayout PanelloginLayout = new javax.swing.GroupLayout(Panellogin);
        Panellogin.setLayout(PanelloginLayout);
        PanelloginLayout.setHorizontalGroup(
            PanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelloginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Buttonotrousuario)
                .addGap(14, 14, 14))
            .addGroup(PanelloginLayout.createSequentialGroup()
                .addGroup(PanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelloginLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jPanellog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelloginLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(Labelnombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );
        PanelloginLayout.setVerticalGroup(
            PanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelloginLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(Labelnombre1)
                .addGap(18, 18, 18)
                .addComponent(jPanellog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Buttonotrousuario)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panellogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Panellogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldnomActionPerformed

    private void ButtonloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonloginActionPerformed
       
        String usuario= TextFieldnom.getText();
        String contrase= PasswordFieldcontra.getText();


        
    if (iniciar.datos.isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "No hay usuarios registrados.");
    } else {
        boolean usuarioEncontrado = false;
        for (Usuarios dato : iniciar.datos) {
            if (dato.getNombre().equals(usuario) && dato.getContra().equals(contrase)) {
                Principal p = new Principal();
                p.setVisible(true);
                this.dispose();
                usuarioEncontrado = true;
                break; 
            }
        }
        if (!usuarioEncontrado) {
            JOptionPane.showMessageDialog(rootPane, "Nombre de usuario o contraseña incorrecta");
            TextFieldnom.setText("");
            PasswordFieldcontra.setText("");
        }
    }
 
        
        
        
       
    }//GEN-LAST:event_ButtonloginActionPerformed

    private void PasswordFieldcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldcontraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldcontraActionPerformed

    private void ButtonotrousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonotrousuarioActionPerformed
        registro reg =new registro();
                reg.setVisible(true);
    }//GEN-LAST:event_ButtonotrousuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttonlogin;
    private javax.swing.JButton Buttonotrousuario;
    private javax.swing.JLabel Labelcontra;
    private javax.swing.JLabel Labelnombre;
    private javax.swing.JLabel Labelnombre1;
    private javax.swing.JPanel Panellogin;
    private javax.swing.JPasswordField PasswordFieldcontra;
    private javax.swing.JTextField TextFieldnom;
    private javax.swing.JPanel jPanellog;
    // End of variables declaration//GEN-END:variables
}
