/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuarto;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import proyecto.Principal;





 
public class fichas extends javax.swing.JFrame {

    /**
     * Creates new form fichas
     */
    
    ArrayList<datos> datos= new ArrayList<>();
    public fichas() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelficha = new javax.swing.JPanel();
        labelfichas = new javax.swing.JLabel();
        labelfichas2 = new javax.swing.JLabel();
        labelfichas3 = new javax.swing.JLabel();
        labelfichas4 = new javax.swing.JLabel();
        TextFieldFnombre = new javax.swing.JTextField();
        TextFieldFcurso = new javax.swing.JTextField();
        TextFieldFtema = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextPanecontenido = new javax.swing.JTextPane();
        labelfichas5 = new javax.swing.JLabel();
        TextFieldnomficha = new javax.swing.JTextField();
        Buttoncrear = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelficha.setBackground(new java.awt.Color(51, 51, 51));

        labelfichas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelfichas.setForeground(new java.awt.Color(255, 255, 255));
        labelfichas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelfichas.setText("Nombre ficha");

        labelfichas2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelfichas2.setForeground(new java.awt.Color(255, 255, 255));
        labelfichas2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelfichas2.setText("Nombre");

        labelfichas3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelfichas3.setForeground(new java.awt.Color(255, 255, 255));
        labelfichas3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelfichas3.setText("Curso");

        labelfichas4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelfichas4.setForeground(new java.awt.Color(255, 255, 255));
        labelfichas4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelfichas4.setText("Tema");

        TextFieldFnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldFnombreActionPerformed(evt);
            }
        });

        TextFieldFcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldFcursoActionPerformed(evt);
            }
        });

        TextFieldFtema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldFtemaActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(TextPanecontenido);

        labelfichas5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelfichas5.setForeground(new java.awt.Color(255, 255, 255));
        labelfichas5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelfichas5.setText("Contenido");

        TextFieldnomficha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldnomfichaActionPerformed(evt);
            }
        });

        Buttoncrear.setText("CrearFicha");
        Buttoncrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtoncrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelfichaLayout = new javax.swing.GroupLayout(panelficha);
        panelficha.setLayout(panelfichaLayout);
        panelfichaLayout.setHorizontalGroup(
            panelfichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfichaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelfichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelfichas5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelfichaLayout.createSequentialGroup()
                        .addGroup(panelfichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelfichas)
                            .addGroup(panelfichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TextFieldnomficha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addComponent(TextFieldFnombre, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(labelfichas2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(panelfichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelfichas4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldFcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelfichas3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldFtema, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelfichaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Buttoncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        panelfichaLayout.setVerticalGroup(
            panelfichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfichaLayout.createSequentialGroup()
                .addGroup(panelfichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelfichaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelfichas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldnomficha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelfichas2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelfichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldFtema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelfichaLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(labelfichas3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextFieldFcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelfichas4)))
                .addGap(46, 46, 46)
                .addComponent(labelfichas5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(Buttoncrear, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        jMenu1.setText("Salir");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelficha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelficha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldFnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldFnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldFnombreActionPerformed

    private void TextFieldFcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldFcursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldFcursoActionPerformed

    private void TextFieldFtemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldFtemaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldFtemaActionPerformed

    private void TextFieldnomfichaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldnomfichaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldnomfichaActionPerformed

    private void ButtoncrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtoncrearActionPerformed
        
        String nombre = TextFieldFnombre.getText();
        String curso = TextFieldFcurso.getText();
        String tema = TextFieldFtema.getText();
        String contenido = TextPanecontenido.getText();
    
        // Guardar los datos de la ficha
        datos nueva = new datos(nombre, curso, tema, contenido);
        datos.add(nueva);
        
        // Crear y guardar el documento PDF
        Date d = new Date();
        logicafichas f = new logicafichas(TextFieldnomficha.getText(), d.toString(), datos);
        f.crearFicha();
        
        JOptionPane.showMessageDialog(rootPane, "Ficha creada y guardada correctamente");
        TextFieldFnombre.setText("");
        TextFieldFcurso.setText("");
        TextFieldFtema.setText("");
        TextPanecontenido.setText("");
        TextFieldnomficha.setText("");
    }//GEN-LAST:event_ButtoncrearActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        Principal principalFrame = new Principal();
        principalFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fichas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fichas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fichas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fichas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fichas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttoncrear;
    private javax.swing.JTextField TextFieldFcurso;
    private javax.swing.JTextField TextFieldFnombre;
    private javax.swing.JTextField TextFieldFtema;
    private javax.swing.JTextField TextFieldnomficha;
    private javax.swing.JTextPane TextPanecontenido;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelfichas;
    private javax.swing.JLabel labelfichas2;
    private javax.swing.JLabel labelfichas3;
    private javax.swing.JLabel labelfichas4;
    private javax.swing.JLabel labelfichas5;
    private javax.swing.JPanel panelficha;
    // End of variables declaration//GEN-END:variables
}
