/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import javax.swing.JOptionPane;
import principal.menu;




 
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panellogin = new javax.swing.JPanel();
        TextFieldnom = new javax.swing.JTextField();
        PasswordFieldcontra = new javax.swing.JPasswordField();
        Buttonlogin = new javax.swing.JButton();
        Labelcontra = new javax.swing.JLabel();
        Labelnombre = new javax.swing.JLabel();
        Buttonotrousuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panellogin.setBackground(new java.awt.Color(51, 51, 51));

        TextFieldnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldnomActionPerformed(evt);
            }
        });

        PasswordFieldcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldcontraActionPerformed(evt);
            }
        });

        Buttonlogin.setText("login");
        Buttonlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonloginActionPerformed(evt);
            }
        });

        Labelcontra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Labelcontra.setForeground(new java.awt.Color(255, 255, 255));
        Labelcontra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labelcontra.setText("Contraseña");

        Labelnombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Labelnombre.setForeground(new java.awt.Color(255, 255, 255));
        Labelnombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Labelnombre.setText("Nombre de usuario");

        Buttonotrousuario.setText("Crear otro usuario");
        Buttonotrousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonotrousuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelloginLayout = new javax.swing.GroupLayout(Panellogin);
        Panellogin.setLayout(PanelloginLayout);
        PanelloginLayout.setHorizontalGroup(
            PanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelloginLayout.createSequentialGroup()
                .addGroup(PanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelloginLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(PanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PasswordFieldcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldnom, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelloginLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(Buttonlogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelloginLayout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addGroup(PanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelloginLayout.createSequentialGroup()
                        .addGroup(PanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Labelnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Labelcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelloginLayout.createSequentialGroup()
                        .addComponent(Buttonotrousuario)
                        .addGap(37, 37, 37))))
        );
        PanelloginLayout.setVerticalGroup(
            PanelloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelloginLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(Labelnombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextFieldnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(Labelcontra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordFieldcontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(Buttonlogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(Buttonotrousuario)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(Panellogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Panellogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldnomActionPerformed
        
    }//GEN-LAST:event_TextFieldnomActionPerformed

    private void ButtonloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonloginActionPerformed
       
        String usuario = TextFieldnom.getText();
        String contrase = PasswordFieldcontra.getText();
        int intentosMaximos = 3;
        int intentos = 0;
        boolean accesoConcedido = false;

for (Usuarios dato : iniciar.datos) {
    if (dato.getNombre().equals(usuario) && dato.getContra().equals(contrase)) {
        menu l =new menu();
        l.setVisible(true);
        this.dispose();
        accesoConcedido = true;
        break;
    }
}

if (!accesoConcedido) {
    intentos = intentos + 1; 
    if (intentos == intentosMaximos) {
        JOptionPane.showMessageDialog(rootPane, "Se han agotado los intentos. Nombre de usuario o contraseña incorrectos.");
        TextFieldnom.setText("");
        PasswordFieldcontra.setText("");
    } else {
        JOptionPane.showMessageDialog(rootPane, "Nombre de usuario o contraseña incorrecta. Intento " + intentos + "/" + intentosMaximos);
        TextFieldnom.setText("");
        PasswordFieldcontra.setText("");
    }
}

       
    }//GEN-LAST:event_ButtonloginActionPerformed

    private void PasswordFieldcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldcontraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldcontraActionPerformed

    private void ButtonotrousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonotrousuarioActionPerformed
        registro reg =new registro();
                reg.setVisible(true);
    }//GEN-LAST:event_ButtonotrousuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buttonlogin;
    private javax.swing.JButton Buttonotrousuario;
    private javax.swing.JLabel Labelcontra;
    private javax.swing.JLabel Labelnombre;
    private javax.swing.JPanel Panellogin;
    private javax.swing.JPasswordField PasswordFieldcontra;
    private javax.swing.JTextField TextFieldnom;
    // End of variables declaration//GEN-END:variables
}
